/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TreasuryInterface extends ethers.utils.Interface {
  functions: {
    "PERIOD()": FunctionFragment;
    "allocateSeigniorage()": FunctionFragment;
    "bondDepletionFloorPercent()": FunctionFragment;
    "bondSupplyExpansionPercent()": FunctionFragment;
    "bondTreasury()": FunctionFragment;
    "bootstrapEpochs()": FunctionFragment;
    "bootstrapSupplyExpansionPercent()": FunctionFragment;
    "buyBonds(uint256,uint256)": FunctionFragment;
    "daoFund()": FunctionFragment;
    "daoFundSharedPercent()": FunctionFragment;
    "devFund()": FunctionFragment;
    "devFundSharedPercent()": FunctionFragment;
    "discountPercent()": FunctionFragment;
    "epoch()": FunctionFragment;
    "epochSupplyContractionLeft()": FunctionFragment;
    "excludedFromTotalSupply(uint256)": FunctionFragment;
    "getBondDiscountRate()": FunctionFragment;
    "getBondPremiumRate()": FunctionFragment;
    "getBurnableGraveLeft()": FunctionFragment;
    "getGraveCirculatingSupply()": FunctionFragment;
    "getGravePrice()": FunctionFragment;
    "getGraveUpdatedPrice()": FunctionFragment;
    "getRedeemableBonds()": FunctionFragment;
    "getReserve()": FunctionFragment;
    "governanceRecoverUnsupported(address,uint256,address)": FunctionFragment;
    "grave()": FunctionFragment;
    "graveOracle()": FunctionFragment;
    "gravePriceCeiling()": FunctionFragment;
    "gravePriceOne()": FunctionFragment;
    "initialize(address,address,address,address,address,address,address,uint256)": FunctionFragment;
    "initialized()": FunctionFragment;
    "isInitialized()": FunctionFragment;
    "masonry()": FunctionFragment;
    "masonryAllocateSeigniorage(uint256)": FunctionFragment;
    "masonryGovernanceRecoverUnsupported(address,uint256,address)": FunctionFragment;
    "masonrySetLockUp(uint256,uint256)": FunctionFragment;
    "masonrySetOperator(address)": FunctionFragment;
    "maxDebtRatioPercent()": FunctionFragment;
    "maxDiscountRate()": FunctionFragment;
    "maxExpansionTiers(uint256)": FunctionFragment;
    "maxPremiumRate()": FunctionFragment;
    "maxSupplyContractionPercent()": FunctionFragment;
    "maxSupplyExpansionPercent()": FunctionFragment;
    "mintingFactorForPayingDebt()": FunctionFragment;
    "nextEpochPoint()": FunctionFragment;
    "operator()": FunctionFragment;
    "premiumPercent()": FunctionFragment;
    "premiumThreshold()": FunctionFragment;
    "previousEpochGravePrice()": FunctionFragment;
    "redeemBonds(uint256,uint256)": FunctionFragment;
    "seigniorageExpansionFloorPercent()": FunctionFragment;
    "seigniorageSaved()": FunctionFragment;
    "setBoardroom(address)": FunctionFragment;
    "setBondDepletionFloorPercent(uint256)": FunctionFragment;
    "setBondSupplyExpansionPercent(uint256)": FunctionFragment;
    "setBondTreasury(address)": FunctionFragment;
    "setBootstrap(uint256,uint256)": FunctionFragment;
    "setDiscountPercent(uint256)": FunctionFragment;
    "setExtraFunds(address,uint256,address,uint256)": FunctionFragment;
    "setGraveOracle(address)": FunctionFragment;
    "setGravePriceCeiling(uint256)": FunctionFragment;
    "setMaxDebtRatioPercent(uint256)": FunctionFragment;
    "setMaxDiscountRate(uint256)": FunctionFragment;
    "setMaxExpansionTiersEntry(uint8,uint256)": FunctionFragment;
    "setMaxPremiumRate(uint256)": FunctionFragment;
    "setMaxSupplyContractionPercent(uint256)": FunctionFragment;
    "setMaxSupplyExpansionPercents(uint256)": FunctionFragment;
    "setMintingFactorForPayingDebt(uint256)": FunctionFragment;
    "setOperator(address)": FunctionFragment;
    "setPremiumPercent(uint256)": FunctionFragment;
    "setPremiumThreshold(uint256)": FunctionFragment;
    "setSupplyTiersEntry(uint8,uint256)": FunctionFragment;
    "startTime()": FunctionFragment;
    "supplyTiers(uint256)": FunctionFragment;
    "xbond()": FunctionFragment;
    "xshare()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "PERIOD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allocateSeigniorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bondDepletionFloorPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bondSupplyExpansionPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bondTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bootstrapEpochs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bootstrapSupplyExpansionPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyBonds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "daoFund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "daoFundSharedPercent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "devFund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "devFundSharedPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "discountPercent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "epoch", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "epochSupplyContractionLeft",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludedFromTotalSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBondDiscountRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBondPremiumRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBurnableGraveLeft",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGraveCirculatingSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGravePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGraveUpdatedPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRedeemableBonds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceRecoverUnsupported",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "grave", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "graveOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gravePriceCeiling",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gravePriceOne",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "masonry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "masonryAllocateSeigniorage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "masonryGovernanceRecoverUnsupported",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "masonrySetLockUp",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "masonrySetOperator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "maxDebtRatioPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxDiscountRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxExpansionTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPremiumRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxSupplyContractionPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxSupplyExpansionPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintingFactorForPayingDebt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextEpochPoint",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "premiumPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "premiumThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previousEpochGravePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeemBonds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seigniorageExpansionFloorPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seigniorageSaved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBoardroom",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setBondDepletionFloorPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBondSupplyExpansionPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBondTreasury",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setBootstrap",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDiscountPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setExtraFunds",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGraveOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setGravePriceCeiling",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxDebtRatioPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxDiscountRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxExpansionTiersEntry",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPremiumRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxSupplyContractionPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxSupplyExpansionPercents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintingFactorForPayingDebt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setOperator", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setPremiumPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPremiumThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupplyTiersEntry",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supplyTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "xbond", values?: undefined): string;
  encodeFunctionData(functionFragment: "xshare", values?: undefined): string;

  decodeFunctionResult(functionFragment: "PERIOD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allocateSeigniorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bondDepletionFloorPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bondSupplyExpansionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bondTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bootstrapEpochs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bootstrapSupplyExpansionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyBonds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "daoFund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoFundSharedPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "devFund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "devFundSharedPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "discountPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epoch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochSupplyContractionLeft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludedFromTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBondDiscountRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBondPremiumRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBurnableGraveLeft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGraveCirculatingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGravePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGraveUpdatedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedeemableBonds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReserve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "governanceRecoverUnsupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grave", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "graveOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gravePriceCeiling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gravePriceOne",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "masonry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "masonryAllocateSeigniorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "masonryGovernanceRecoverUnsupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "masonrySetLockUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "masonrySetOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDebtRatioPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDiscountRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxExpansionTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPremiumRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSupplyContractionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSupplyExpansionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintingFactorForPayingDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEpochPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "premiumPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "premiumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previousEpochGravePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemBonds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seigniorageExpansionFloorPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seigniorageSaved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBoardroom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBondDepletionFloorPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBondSupplyExpansionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBondTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBootstrap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDiscountPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExtraFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGraveOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGravePriceCeiling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxDebtRatioPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxDiscountRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxExpansionTiersEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPremiumRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxSupplyContractionPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxSupplyExpansionPercents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintingFactorForPayingDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPremiumPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPremiumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupplyTiersEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supplyTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xbond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xshare", data: BytesLike): Result;

  events: {
    "BoardroomFunded(uint256,uint256)": EventFragment;
    "BoughtBonds(address,uint256,uint256)": EventFragment;
    "BurnedBonds(address,uint256)": EventFragment;
    "DaoFundFunded(uint256,uint256)": EventFragment;
    "DevFundFunded(uint256,uint256)": EventFragment;
    "Initialized(address,uint256)": EventFragment;
    "RedeemedBonds(address,uint256,uint256)": EventFragment;
    "TreasuryFunded(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BoardroomFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BoughtBonds"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BurnedBonds"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DaoFundFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DevFundFunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RedeemedBonds"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TreasuryFunded"): EventFragment;
}

export type BoardroomFundedEvent = TypedEvent<
  [BigNumber, BigNumber] & { timestamp: BigNumber; seigniorage: BigNumber }
>;

export type BoughtBondsEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    from: string;
    graveAmount: BigNumber;
    bondAmount: BigNumber;
  }
>;

export type BurnedBondsEvent = TypedEvent<
  [string, BigNumber] & { from: string; bondAmount: BigNumber }
>;

export type DaoFundFundedEvent = TypedEvent<
  [BigNumber, BigNumber] & { timestamp: BigNumber; seigniorage: BigNumber }
>;

export type DevFundFundedEvent = TypedEvent<
  [BigNumber, BigNumber] & { timestamp: BigNumber; seigniorage: BigNumber }
>;

export type InitializedEvent = TypedEvent<
  [string, BigNumber] & { executor: string; at: BigNumber }
>;

export type RedeemedBondsEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    from: string;
    graveAmount: BigNumber;
    bondAmount: BigNumber;
  }
>;

export type TreasuryFundedEvent = TypedEvent<
  [BigNumber, BigNumber] & { timestamp: BigNumber; seigniorage: BigNumber }
>;

export class Treasury extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TreasuryInterface;

  functions: {
    PERIOD(overrides?: CallOverrides): Promise<[BigNumber]>;

    allocateSeigniorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bondDepletionFloorPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    bondSupplyExpansionPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    bondTreasury(overrides?: CallOverrides): Promise<[string]>;

    bootstrapEpochs(overrides?: CallOverrides): Promise<[BigNumber]>;

    bootstrapSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    buyBonds(
      _graveAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    daoFund(overrides?: CallOverrides): Promise<[string]>;

    daoFundSharedPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    devFund(overrides?: CallOverrides): Promise<[string]>;

    devFundSharedPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    discountPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    epoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    epochSupplyContractionLeft(overrides?: CallOverrides): Promise<[BigNumber]>;

    excludedFromTotalSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getBondDiscountRate(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _rate: BigNumber }>;

    getBondPremiumRate(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _rate: BigNumber }>;

    getBurnableGraveLeft(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _burnableGraveLeft: BigNumber }>;

    getGraveCirculatingSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGravePrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { gravePrice: BigNumber }>;

    getGraveUpdatedPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _gravePrice: BigNumber }>;

    getRedeemableBonds(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _redeemableBonds: BigNumber }>;

    getReserve(overrides?: CallOverrides): Promise<[BigNumber]>;

    governanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    grave(overrides?: CallOverrides): Promise<[string]>;

    graveOracle(overrides?: CallOverrides): Promise<[string]>;

    gravePriceCeiling(overrides?: CallOverrides): Promise<[BigNumber]>;

    gravePriceOne(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      _grave: string,
      _xbond: string,
      _xshare: string,
      _graveOracle: string,
      _masonry: string,
      _genesisPool: string,
      _bondTreasury: string,
      _startTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialized(overrides?: CallOverrides): Promise<[boolean]>;

    isInitialized(overrides?: CallOverrides): Promise<[boolean]>;

    masonry(overrides?: CallOverrides): Promise<[string]>;

    masonryAllocateSeigniorage(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    masonryGovernanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    masonrySetLockUp(
      _withdrawLockupEpochs: BigNumberish,
      _rewardLockupEpochs: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    masonrySetOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    maxDebtRatioPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxDiscountRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxExpansionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxPremiumRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxSupplyContractionPercent(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxSupplyExpansionPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    mintingFactorForPayingDebt(overrides?: CallOverrides): Promise<[BigNumber]>;

    nextEpochPoint(overrides?: CallOverrides): Promise<[BigNumber]>;

    operator(overrides?: CallOverrides): Promise<[string]>;

    premiumPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    premiumThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    previousEpochGravePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    redeemBonds(
      _bondAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    seigniorageExpansionFloorPercent(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    seigniorageSaved(overrides?: CallOverrides): Promise<[BigNumber]>;

    setBoardroom(
      _masonry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBondDepletionFloorPercent(
      _bondDepletionFloorPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBondSupplyExpansionPercent(
      _bondSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBondTreasury(
      _bondTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBootstrap(
      _bootstrapEpochs: BigNumberish,
      _bootstrapSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDiscountPercent(
      _discountPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setExtraFunds(
      _daoFund: string,
      _daoFundSharedPercent: BigNumberish,
      _devFund: string,
      _devFundSharedPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGraveOracle(
      _graveOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGravePriceCeiling(
      _gravePriceCeiling: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxDebtRatioPercent(
      _maxDebtRatioPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxDiscountRate(
      _maxDiscountRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxExpansionTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxPremiumRate(
      _maxPremiumRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxSupplyContractionPercent(
      _maxSupplyContractionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxSupplyExpansionPercents(
      _maxSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMintingFactorForPayingDebt(
      _mintingFactorForPayingDebt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPremiumPercent(
      _premiumPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPremiumThreshold(
      _premiumThreshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSupplyTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    startTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    supplyTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    xbond(overrides?: CallOverrides): Promise<[string]>;

    xshare(overrides?: CallOverrides): Promise<[string]>;
  };

  PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

  allocateSeigniorage(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bondDepletionFloorPercent(overrides?: CallOverrides): Promise<BigNumber>;

  bondSupplyExpansionPercent(overrides?: CallOverrides): Promise<BigNumber>;

  bondTreasury(overrides?: CallOverrides): Promise<string>;

  bootstrapEpochs(overrides?: CallOverrides): Promise<BigNumber>;

  bootstrapSupplyExpansionPercent(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  buyBonds(
    _graveAmount: BigNumberish,
    targetPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  daoFund(overrides?: CallOverrides): Promise<string>;

  daoFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

  devFund(overrides?: CallOverrides): Promise<string>;

  devFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

  discountPercent(overrides?: CallOverrides): Promise<BigNumber>;

  epoch(overrides?: CallOverrides): Promise<BigNumber>;

  epochSupplyContractionLeft(overrides?: CallOverrides): Promise<BigNumber>;

  excludedFromTotalSupply(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getBondDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

  getBondPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

  getBurnableGraveLeft(overrides?: CallOverrides): Promise<BigNumber>;

  getGraveCirculatingSupply(overrides?: CallOverrides): Promise<BigNumber>;

  getGravePrice(overrides?: CallOverrides): Promise<BigNumber>;

  getGraveUpdatedPrice(overrides?: CallOverrides): Promise<BigNumber>;

  getRedeemableBonds(overrides?: CallOverrides): Promise<BigNumber>;

  getReserve(overrides?: CallOverrides): Promise<BigNumber>;

  governanceRecoverUnsupported(
    _token: string,
    _amount: BigNumberish,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  grave(overrides?: CallOverrides): Promise<string>;

  graveOracle(overrides?: CallOverrides): Promise<string>;

  gravePriceCeiling(overrides?: CallOverrides): Promise<BigNumber>;

  gravePriceOne(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    _grave: string,
    _xbond: string,
    _xshare: string,
    _graveOracle: string,
    _masonry: string,
    _genesisPool: string,
    _bondTreasury: string,
    _startTime: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialized(overrides?: CallOverrides): Promise<boolean>;

  isInitialized(overrides?: CallOverrides): Promise<boolean>;

  masonry(overrides?: CallOverrides): Promise<string>;

  masonryAllocateSeigniorage(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  masonryGovernanceRecoverUnsupported(
    _token: string,
    _amount: BigNumberish,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  masonrySetLockUp(
    _withdrawLockupEpochs: BigNumberish,
    _rewardLockupEpochs: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  masonrySetOperator(
    _operator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  maxDebtRatioPercent(overrides?: CallOverrides): Promise<BigNumber>;

  maxDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

  maxExpansionTiers(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

  maxSupplyContractionPercent(overrides?: CallOverrides): Promise<BigNumber>;

  maxSupplyExpansionPercent(overrides?: CallOverrides): Promise<BigNumber>;

  mintingFactorForPayingDebt(overrides?: CallOverrides): Promise<BigNumber>;

  nextEpochPoint(overrides?: CallOverrides): Promise<BigNumber>;

  operator(overrides?: CallOverrides): Promise<string>;

  premiumPercent(overrides?: CallOverrides): Promise<BigNumber>;

  premiumThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  previousEpochGravePrice(overrides?: CallOverrides): Promise<BigNumber>;

  redeemBonds(
    _bondAmount: BigNumberish,
    targetPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  seigniorageExpansionFloorPercent(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  seigniorageSaved(overrides?: CallOverrides): Promise<BigNumber>;

  setBoardroom(
    _masonry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBondDepletionFloorPercent(
    _bondDepletionFloorPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBondSupplyExpansionPercent(
    _bondSupplyExpansionPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBondTreasury(
    _bondTreasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBootstrap(
    _bootstrapEpochs: BigNumberish,
    _bootstrapSupplyExpansionPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDiscountPercent(
    _discountPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setExtraFunds(
    _daoFund: string,
    _daoFundSharedPercent: BigNumberish,
    _devFund: string,
    _devFundSharedPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGraveOracle(
    _graveOracle: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGravePriceCeiling(
    _gravePriceCeiling: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxDebtRatioPercent(
    _maxDebtRatioPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxDiscountRate(
    _maxDiscountRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxExpansionTiersEntry(
    _index: BigNumberish,
    _value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxPremiumRate(
    _maxPremiumRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxSupplyContractionPercent(
    _maxSupplyContractionPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxSupplyExpansionPercents(
    _maxSupplyExpansionPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMintingFactorForPayingDebt(
    _mintingFactorForPayingDebt: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOperator(
    _operator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPremiumPercent(
    _premiumPercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPremiumThreshold(
    _premiumThreshold: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSupplyTiersEntry(
    _index: BigNumberish,
    _value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  startTime(overrides?: CallOverrides): Promise<BigNumber>;

  supplyTiers(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  xbond(overrides?: CallOverrides): Promise<string>;

  xshare(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    allocateSeigniorage(overrides?: CallOverrides): Promise<void>;

    bondDepletionFloorPercent(overrides?: CallOverrides): Promise<BigNumber>;

    bondSupplyExpansionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    bondTreasury(overrides?: CallOverrides): Promise<string>;

    bootstrapEpochs(overrides?: CallOverrides): Promise<BigNumber>;

    bootstrapSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyBonds(
      _graveAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    daoFund(overrides?: CallOverrides): Promise<string>;

    daoFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

    devFund(overrides?: CallOverrides): Promise<string>;

    devFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

    discountPercent(overrides?: CallOverrides): Promise<BigNumber>;

    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    epochSupplyContractionLeft(overrides?: CallOverrides): Promise<BigNumber>;

    excludedFromTotalSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getBondDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

    getBondPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

    getBurnableGraveLeft(overrides?: CallOverrides): Promise<BigNumber>;

    getGraveCirculatingSupply(overrides?: CallOverrides): Promise<BigNumber>;

    getGravePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getGraveUpdatedPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getRedeemableBonds(overrides?: CallOverrides): Promise<BigNumber>;

    getReserve(overrides?: CallOverrides): Promise<BigNumber>;

    governanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    grave(overrides?: CallOverrides): Promise<string>;

    graveOracle(overrides?: CallOverrides): Promise<string>;

    gravePriceCeiling(overrides?: CallOverrides): Promise<BigNumber>;

    gravePriceOne(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _grave: string,
      _xbond: string,
      _xshare: string,
      _graveOracle: string,
      _masonry: string,
      _genesisPool: string,
      _bondTreasury: string,
      _startTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    initialized(overrides?: CallOverrides): Promise<boolean>;

    isInitialized(overrides?: CallOverrides): Promise<boolean>;

    masonry(overrides?: CallOverrides): Promise<string>;

    masonryAllocateSeigniorage(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    masonryGovernanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    masonrySetLockUp(
      _withdrawLockupEpochs: BigNumberish,
      _rewardLockupEpochs: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    masonrySetOperator(
      _operator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    maxDebtRatioPercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

    maxExpansionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

    maxSupplyContractionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxSupplyExpansionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    mintingFactorForPayingDebt(overrides?: CallOverrides): Promise<BigNumber>;

    nextEpochPoint(overrides?: CallOverrides): Promise<BigNumber>;

    operator(overrides?: CallOverrides): Promise<string>;

    premiumPercent(overrides?: CallOverrides): Promise<BigNumber>;

    premiumThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    previousEpochGravePrice(overrides?: CallOverrides): Promise<BigNumber>;

    redeemBonds(
      _bondAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    seigniorageExpansionFloorPercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seigniorageSaved(overrides?: CallOverrides): Promise<BigNumber>;

    setBoardroom(_masonry: string, overrides?: CallOverrides): Promise<void>;

    setBondDepletionFloorPercent(
      _bondDepletionFloorPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setBondSupplyExpansionPercent(
      _bondSupplyExpansionPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setBondTreasury(
      _bondTreasury: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setBootstrap(
      _bootstrapEpochs: BigNumberish,
      _bootstrapSupplyExpansionPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDiscountPercent(
      _discountPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setExtraFunds(
      _daoFund: string,
      _daoFundSharedPercent: BigNumberish,
      _devFund: string,
      _devFundSharedPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setGraveOracle(
      _graveOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setGravePriceCeiling(
      _gravePriceCeiling: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxDebtRatioPercent(
      _maxDebtRatioPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxDiscountRate(
      _maxDiscountRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxExpansionTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setMaxPremiumRate(
      _maxPremiumRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxSupplyContractionPercent(
      _maxSupplyContractionPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxSupplyExpansionPercents(
      _maxSupplyExpansionPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMintingFactorForPayingDebt(
      _mintingFactorForPayingDebt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setOperator(_operator: string, overrides?: CallOverrides): Promise<void>;

    setPremiumPercent(
      _premiumPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPremiumThreshold(
      _premiumThreshold: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSupplyTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    supplyTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    xbond(overrides?: CallOverrides): Promise<string>;

    xshare(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "BoardroomFunded(uint256,uint256)"(
      timestamp?: null,
      seigniorage?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { timestamp: BigNumber; seigniorage: BigNumber }
    >;

    BoardroomFunded(
      timestamp?: null,
      seigniorage?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { timestamp: BigNumber; seigniorage: BigNumber }
    >;

    "BoughtBonds(address,uint256,uint256)"(
      from?: string | null,
      graveAmount?: null,
      bondAmount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { from: string; graveAmount: BigNumber; bondAmount: BigNumber }
    >;

    BoughtBonds(
      from?: string | null,
      graveAmount?: null,
      bondAmount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { from: string; graveAmount: BigNumber; bondAmount: BigNumber }
    >;

    "BurnedBonds(address,uint256)"(
      from?: string | null,
      bondAmount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; bondAmount: BigNumber }
    >;

    BurnedBonds(
      from?: string | null,
      bondAmount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; bondAmount: BigNumber }
    >;

    "DaoFundFunded(uint256,uint256)"(
      timestamp?: null,
      seigniorage?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { timestamp: BigNumber; seigniorage: BigNumber }
    >;

    DaoFundFunded(
      timestamp?: null,
      seigniorage?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { timestamp: BigNumber; seigniorage: BigNumber }
    >;

    "DevFundFunded(uint256,uint256)"(
      timestamp?: null,
      seigniorage?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { timestamp: BigNumber; seigniorage: BigNumber }
    >;

    DevFundFunded(
      timestamp?: null,
      seigniorage?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { timestamp: BigNumber; seigniorage: BigNumber }
    >;

    "Initialized(address,uint256)"(
      executor?: string | null,
      at?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { executor: string; at: BigNumber }
    >;

    Initialized(
      executor?: string | null,
      at?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { executor: string; at: BigNumber }
    >;

    "RedeemedBonds(address,uint256,uint256)"(
      from?: string | null,
      graveAmount?: null,
      bondAmount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { from: string; graveAmount: BigNumber; bondAmount: BigNumber }
    >;

    RedeemedBonds(
      from?: string | null,
      graveAmount?: null,
      bondAmount?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { from: string; graveAmount: BigNumber; bondAmount: BigNumber }
    >;

    "TreasuryFunded(uint256,uint256)"(
      timestamp?: null,
      seigniorage?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { timestamp: BigNumber; seigniorage: BigNumber }
    >;

    TreasuryFunded(
      timestamp?: null,
      seigniorage?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { timestamp: BigNumber; seigniorage: BigNumber }
    >;
  };

  estimateGas: {
    PERIOD(overrides?: CallOverrides): Promise<BigNumber>;

    allocateSeigniorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bondDepletionFloorPercent(overrides?: CallOverrides): Promise<BigNumber>;

    bondSupplyExpansionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    bondTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    bootstrapEpochs(overrides?: CallOverrides): Promise<BigNumber>;

    bootstrapSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyBonds(
      _graveAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    daoFund(overrides?: CallOverrides): Promise<BigNumber>;

    daoFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

    devFund(overrides?: CallOverrides): Promise<BigNumber>;

    devFundSharedPercent(overrides?: CallOverrides): Promise<BigNumber>;

    discountPercent(overrides?: CallOverrides): Promise<BigNumber>;

    epoch(overrides?: CallOverrides): Promise<BigNumber>;

    epochSupplyContractionLeft(overrides?: CallOverrides): Promise<BigNumber>;

    excludedFromTotalSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBondDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

    getBondPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

    getBurnableGraveLeft(overrides?: CallOverrides): Promise<BigNumber>;

    getGraveCirculatingSupply(overrides?: CallOverrides): Promise<BigNumber>;

    getGravePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getGraveUpdatedPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getRedeemableBonds(overrides?: CallOverrides): Promise<BigNumber>;

    getReserve(overrides?: CallOverrides): Promise<BigNumber>;

    governanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    grave(overrides?: CallOverrides): Promise<BigNumber>;

    graveOracle(overrides?: CallOverrides): Promise<BigNumber>;

    gravePriceCeiling(overrides?: CallOverrides): Promise<BigNumber>;

    gravePriceOne(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _grave: string,
      _xbond: string,
      _xshare: string,
      _graveOracle: string,
      _masonry: string,
      _genesisPool: string,
      _bondTreasury: string,
      _startTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialized(overrides?: CallOverrides): Promise<BigNumber>;

    isInitialized(overrides?: CallOverrides): Promise<BigNumber>;

    masonry(overrides?: CallOverrides): Promise<BigNumber>;

    masonryAllocateSeigniorage(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    masonryGovernanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    masonrySetLockUp(
      _withdrawLockupEpochs: BigNumberish,
      _rewardLockupEpochs: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    masonrySetOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    maxDebtRatioPercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxDiscountRate(overrides?: CallOverrides): Promise<BigNumber>;

    maxExpansionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxPremiumRate(overrides?: CallOverrides): Promise<BigNumber>;

    maxSupplyContractionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    maxSupplyExpansionPercent(overrides?: CallOverrides): Promise<BigNumber>;

    mintingFactorForPayingDebt(overrides?: CallOverrides): Promise<BigNumber>;

    nextEpochPoint(overrides?: CallOverrides): Promise<BigNumber>;

    operator(overrides?: CallOverrides): Promise<BigNumber>;

    premiumPercent(overrides?: CallOverrides): Promise<BigNumber>;

    premiumThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    previousEpochGravePrice(overrides?: CallOverrides): Promise<BigNumber>;

    redeemBonds(
      _bondAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    seigniorageExpansionFloorPercent(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seigniorageSaved(overrides?: CallOverrides): Promise<BigNumber>;

    setBoardroom(
      _masonry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBondDepletionFloorPercent(
      _bondDepletionFloorPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBondSupplyExpansionPercent(
      _bondSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBondTreasury(
      _bondTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBootstrap(
      _bootstrapEpochs: BigNumberish,
      _bootstrapSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDiscountPercent(
      _discountPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setExtraFunds(
      _daoFund: string,
      _daoFundSharedPercent: BigNumberish,
      _devFund: string,
      _devFundSharedPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGraveOracle(
      _graveOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGravePriceCeiling(
      _gravePriceCeiling: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxDebtRatioPercent(
      _maxDebtRatioPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxDiscountRate(
      _maxDiscountRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxExpansionTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxPremiumRate(
      _maxPremiumRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxSupplyContractionPercent(
      _maxSupplyContractionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxSupplyExpansionPercents(
      _maxSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMintingFactorForPayingDebt(
      _mintingFactorForPayingDebt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPremiumPercent(
      _premiumPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPremiumThreshold(
      _premiumThreshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSupplyTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    supplyTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    xbond(overrides?: CallOverrides): Promise<BigNumber>;

    xshare(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    PERIOD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allocateSeigniorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bondDepletionFloorPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bondSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bondTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bootstrapEpochs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bootstrapSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyBonds(
      _graveAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    daoFund(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    daoFundSharedPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    devFund(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    devFundSharedPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    discountPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochSupplyContractionLeft(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    excludedFromTotalSupply(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBondDiscountRate(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBondPremiumRate(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBurnableGraveLeft(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGraveCirculatingSupply(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGravePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGraveUpdatedPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRedeemableBonds(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReserve(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    grave(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    graveOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gravePriceCeiling(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gravePriceOne(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _grave: string,
      _xbond: string,
      _xshare: string,
      _graveOracle: string,
      _masonry: string,
      _genesisPool: string,
      _bondTreasury: string,
      _startTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isInitialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    masonry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    masonryAllocateSeigniorage(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    masonryGovernanceRecoverUnsupported(
      _token: string,
      _amount: BigNumberish,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    masonrySetLockUp(
      _withdrawLockupEpochs: BigNumberish,
      _rewardLockupEpochs: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    masonrySetOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    maxDebtRatioPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxDiscountRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxExpansionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxPremiumRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxSupplyContractionPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxSupplyExpansionPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintingFactorForPayingDebt(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextEpochPoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    operator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    premiumPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    premiumThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    previousEpochGravePrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    redeemBonds(
      _bondAmount: BigNumberish,
      targetPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    seigniorageExpansionFloorPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seigniorageSaved(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setBoardroom(
      _masonry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBondDepletionFloorPercent(
      _bondDepletionFloorPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBondSupplyExpansionPercent(
      _bondSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBondTreasury(
      _bondTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBootstrap(
      _bootstrapEpochs: BigNumberish,
      _bootstrapSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDiscountPercent(
      _discountPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setExtraFunds(
      _daoFund: string,
      _daoFundSharedPercent: BigNumberish,
      _devFund: string,
      _devFundSharedPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGraveOracle(
      _graveOracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGravePriceCeiling(
      _gravePriceCeiling: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxDebtRatioPercent(
      _maxDebtRatioPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxDiscountRate(
      _maxDiscountRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxExpansionTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxPremiumRate(
      _maxPremiumRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxSupplyContractionPercent(
      _maxSupplyContractionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxSupplyExpansionPercents(
      _maxSupplyExpansionPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMintingFactorForPayingDebt(
      _mintingFactorForPayingDebt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOperator(
      _operator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPremiumPercent(
      _premiumPercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPremiumThreshold(
      _premiumThreshold: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSupplyTiersEntry(
      _index: BigNumberish,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    startTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supplyTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    xbond(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    xshare(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
